### PR TITLE
issue-33[add correct ids to input fields]

### LINKED ISSUE #33: Programming Expertise Accessibility Issue
### Description

1. Make sure all input fields are accessible.

Currently, the axe DevTools are showing that

> 
> Issue Description
> 
> Ensures form field does not have multiple label elements

To reproduce the issue, install the axe DevTools extension and run it.

### Screenshots

_No response_

### Additional information

For further instructions on how to make the component accessible, please read the following:

- [Form field multiple labels](https://dequeuniversity.com/rules/axe/4.4/form-field-multiple-labels?application=AxeFirefox)
- [IDs used in ARIA and labels must be unique ](https://dequeuniversity.com/rules/axe/4.4/duplicate-id-aria?application=AxeFirefox)

### PR DESCRIPTION
**Pull request by hariscs**
_For an example of how to fill this template out, [see this Pull Request in the Wiki](https://github.com/YurisCodingClub/DevCV/wiki/How-to-create-a-pull-request)._ 

## Description
added correct ids to input fields

## Related Issue
programming expertise accessibility issue. closes #33  

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|✓ | :bug: Bug fix              |
|    | :sparkles: New feature     |
|    | :hammer: Refactoring       |
|    | :100: Add tests            |
|    | :link: Update dependencies |
|    | :scroll: Docs              |

### CODE REVIEW

**Comment by YuriDevAT** [comment]
Hey @hariscs. Thanks for your contribution. Actually I cannot see any changes in the programming expertise file. Also, I cannot see the error anymore, so I guess it was handled by making changes in another file from another PR I merged this week. Therefore, I have to close this PR and Issue.

**Comment by hariscs** [comment]
It was a small change, in the `personal information` component the job title inputs had the wrong id so I changed that. The rest of the files were working fine.

**Comment by YuriDevAT** [comment]
I see. Please refrain from changing other things then the issue describes. I most likely opened other issues for that. Also, please refrain from opening PRs when the issue is not assigned to you.

**Comment by hariscs** [comment]
Got it, thanks

**Pull request closed without merging**
