### PR TITLE
Added a download button #9

### LINKED ISSUE #9: [FEATURE] Button Download
### Description

Create a button called Download with an icon next to the text.

### Acceptance Criteria (AC)

- [ ] Create a component called `DownloadButton.js` and save it in a folder called **components** in the `src` directory
- [ ] The icon has to be an svg
- [ ] Create a folder in the public directory and call it "images"
- [ ] Save the svg in the new folder called "images"
- [ ] Button does not require functionality
- [ ] No stylings but plain html
- [ ] The new component is imported and displayed in the `App.js` component
- [ ] Only the new component is displayed

### Screenshots

_No response_

### Additional information

Please do not hesitate to ask me about accessible forms in case you are unsure.
Accessibility and your inexperience with this topic should not be the reason you are not work on this issue, but to learn about it.

### PR DESCRIPTION
**Pull request by DugarRishab**
## Description

- Download button was created and imported in `app.jsx`. 
- `app.js` was renamed as `app.jsx`.
- closes #9 

## Related Issue

Instead of downloading and linking a svg, we should use material icons instead, because of the following reasons: 
- Using Material Icons is cleaner ad easier. 
- Material icons work even with poorest internet connection. 
- We will not have to handle any extra files. 

## Acceptance Criteria

- [x] Create a component called DownloadButton.js and save it in a folder called components in the src directory
- [x]  The icon has to be an svg
- [x]  Create a folder in the public directory and call it "images"
- [x]  Save the svg in the new folder called "images"
- [x]  Button does not require functionality
- [x]  No stylings but plain html
- [x]  The new component is imported and displayed in the App.js component
- [x]  Only the new component is displayed

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|    | :bug: Bug fix              |
| ✓ | :sparkles: New feature     |
|    | :hammer: Refactoring       |
|    | :100: Add tests            |
|    | :link: Update dependencies |
|    | :scroll: Docs              |

### Before

Default template react app

### After

Blank page with just a download button

image

## Testing Steps / QA Criteria

No tests required

### CODE REVIEW

**Comment by DugarRishab** [comment]
Upon inspection, I discovered that the error was created because of `unused variables` in the code. 

## Solutions
- Add `CI = false` in env variables in Netlify
- OR, remove unused variables from the code. 

## Recommendation
- Add `CI = false` in env variables in Netlify to avoid future problems.

**Comment by DugarRishab** [comment]
@YuriDevAT I cannot figure out why the 1st test (greeting) is failing.

**Comment by Mohit-Aasirwal** [comment]
> @YuriDevAT I cannot figure out why the 1st test (greeting) is failing.

I even don't know how to fix that in my own PR.

**Comment by YuriDevAT** [comment]
Thank you for your patience. I am so sorry that there were problems with the yml file.

**Review by YuriDevAT — APPROVED** [review]
Thank you for your contribution. I think changing the js file to jsx is not really needed.

I will create a discussion soon for material UI, thanks for the suggestion.

**Pull request merged**
